name: restful
description: A starting point for Dart Restful Api package, for Using Api(HTTP) to Easyly access server info, see demo or examples.
version: 0.0.2
homepage: https://gitee.com/darto/restful

## pub publish --server=https://pub.dartlang.org
##

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.2.2
  crypto: ^2.1.5
  http: ^0.12.1
  mime: ^0.9.7
  convert: ^2.1.1
  mongo_dart: ^0.4.2
  shelf_proxy: ^0.1.0+7
  uuid: ^2.2.2
  process_run: ^0.10.12+3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
