name: restful
description: A starting point for Dart Restful Api package, for Using Api(HTTP) to Easyly access server info, see demo or examples.
version: 0.0.3
homepage: https://gitee.com/darto/restful

## pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.2.2
  crypto: ^2.1.5
  http: ^0.12.1
  mime: ^0.9.7
  convert: ^2.1.1
  pro: ^0.0.4
  alm: ^0.0.5
