name: restful
description: A starting point for Dart Restful Api package, for Using Api(HTTP) to Easyly access server info, see demo or examples.
version: 0.0.1
homepage: https://github.com/almpazel/dart-restful

## pub publish --server=https://pub.dartlang.org
## dart example/example.dart
## nohup dart example/example.dart > example.log 2>&1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.1
  convert: ^2.1.1
  meta: any

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
